export const mockGenresStats = [
  { genre_id: 1, slug: 'accion', name_es: 'Acción', name_en: 'Action', media_count: 245 },
  { genre_id: 2, slug: 'aventura', name_es: 'Aventura', name_en: 'Adventure', media_count: 189 },
  { genre_id: 3, slug: 'animacion', name_es: 'Animación', name_en: 'Animation', media_count: 156 },
  { genre_id: 4, slug: 'comedia', name_es: 'Comedia', name_en: 'Comedy', media_count: 312 },
  { genre_id: 5, slug: 'crimen', name_es: 'Crimen', name_en: 'Crime', media_count: 98 },
  { genre_id: 6, slug: 'documental', name_es: 'Documental', name_en: 'Documentary', media_count: 67 },
  { genre_id: 7, slug: 'drama', name_es: 'Drama', name_en: 'Drama', media_count: 423 },
  { genre_id: 8, slug: 'familia', name_es: 'Familia', name_en: 'Family', media_count: 134 },
  { genre_id: 9, slug: 'fantasia', name_es: 'Fantasía', name_en: 'Fantasy', media_count: 178 },
  { genre_id: 10, slug: 'historia', name_es: 'Historia', name_en: 'History', media_count: 45 },
  { genre_id: 11, slug: 'terror', name_es: 'Terror', name_en: 'Horror', media_count: 203 },
  { genre_id: 12, slug: 'musica', name_es: 'Música', name_en: 'Music', media_count: 56 },
  { genre_id: 13, slug: 'misterio', name_es: 'Misterio', name_en: 'Mystery', media_count: 112 },
  { genre_id: 14, slug: 'romance', name_es: 'Romance', name_en: 'Romance', media_count: 267 },
  { genre_id: 15, slug: 'ciencia-ficcion', name_es: 'Ciencia Ficción', name_en: 'Science Fiction', media_count: 189 },
  { genre_id: 16, slug: 'tv-movie', name_es: 'Película de TV', name_en: 'TV Movie', media_count: 23 },
  { genre_id: 17, slug: 'thriller', name_es: 'Thriller', name_en: 'Thriller', media_count: 178 },
  { genre_id: 18, slug: 'guerra', name_es: 'Guerra', name_en: 'War', media_count: 78 },
  { genre_id: 19, slug: 'western', name_es: 'Western', name_en: 'Western', media_count: 34 }
]

export const mockGenres = [
  {
    id: 1,
    tmdb_id: 28,
    slug: 'accion',
    name_es: 'Acción',
    name_en: 'Action',
    description_es: 'Películas llenas de adrenalina con escenas emocionantes de combate, persecuciones y explosiones.',
    description_en: 'Adrenaline-packed movies with exciting combat scenes, chases, and explosions.',
    cover_image_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200',
    status: 'published',
    sitemap_priority: 'high',
    seo_title_es: 'Las Mejores Películas de Acción en Streaming',
    seo_title_en: 'Best Action Movies Streaming',
    seo_description_es: 'Descubre las mejores películas de acción disponibles en streaming. Desde clásicos hasta los últimos estrenos.',
    seo_description_en: 'Discover the best action movies available on streaming. From classics to the latest releases.'
  },
  {
    id: 2,
    tmdb_id: 12,
    slug: 'aventura',
    name_es: 'Aventura',
    name_en: 'Adventure',
    description_es: 'Viajes épicos a lugares exóticos con héroes que enfrentan peligros increíbles.',
    description_en: 'Epic journeys to exotic places with heroes facing incredible dangers.',
    cover_image_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 3,
    tmdb_id: 16,
    slug: 'animacion',
    name_es: 'Animación',
    name_en: 'Animation',
    description_es: 'Mundos imaginarios cobran vida a través del arte de la animación.',
    description_en: 'Imaginary worlds come to life through the art of animation.',
    cover_image_url: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 4,
    tmdb_id: 35,
    slug: 'comedia',
    name_es: 'Comedia',
    name_en: 'Comedy',
    description_es: 'Risas garantizadas con situaciones divertidas y personajes entrañables.',
    description_en: 'Guaranteed laughs with funny situations and lovable characters.',
    cover_image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 5,
    tmdb_id: 80,
    slug: 'crimen',
    name_es: 'Crimen',
    name_en: 'Crime',
    description_es: 'Historias de detectives, ladrones y el lado oscuro de la sociedad.',
    description_en: 'Stories of detectives, thieves, and the dark side of society.',
    cover_image_url: 'https://images.unsplash.com/photo-1509248961895-403493d877b5?w=1200',
    status: 'published',
    sitemap_priority: 'medium'
  },
  {
    id: 6,
    tmdb_id: 99,
    slug: 'documental',
    name_es: 'Documental',
    name_en: 'Documentary',
    description_es: 'Historias reales que educan e inspiran sobre el mundo que nos rodea.',
    description_en: 'Real stories that educate and inspire about the world around us.',
    cover_image_url: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200',
    status: 'published',
    sitemap_priority: 'medium'
  },
  {
    id: 7,
    tmdb_id: 18,
    slug: 'drama',
    name_es: 'Drama',
    name_en: 'Drama',
    description_es: 'Historias emotivas que exploran la condición humana y las relaciones.',
    description_en: 'Emotional stories exploring the human condition and relationships.',
    cover_image_url: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 8,
    tmdb_id: 10751,
    slug: 'familia',
    name_es: 'Familia',
    name_en: 'Family',
    description_es: 'Películas perfectas para disfrutar en compañía de toda la familia.',
    description_en: 'Perfect movies to enjoy with the whole family.',
    cover_image_url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 9,
    tmdb_id: 14,
    slug: 'fantasia',
    name_es: 'Fantasía',
    name_en: 'Fantasy',
    description_es: 'Mundos mágicos con criaturas fantásticas y poderes sobrenaturales.',
    description_en: 'Magical worlds with fantastic creatures and supernatural powers.',
    cover_image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 10,
    tmdb_id: 36,
    slug: 'historia',
    name_es: 'Historia',
    name_en: 'History',
    description_es: 'Recreaciones de eventos históricos que marcaron el mundo.',
    description_en: 'Recreations of historical events that shaped the world.',
    cover_image_url: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=1200',
    status: 'published',
    sitemap_priority: 'medium'
  },
  {
    id: 11,
    tmdb_id: 27,
    slug: 'terror',
    name_es: 'Terror',
    name_en: 'Horror',
    description_es: 'Películas que te harán temblar con sustos y terror psicológico.',
    description_en: 'Movies that will make you tremble with scares and psychological horror.',
    cover_image_url: 'https://images.unsplash.com/photo-1509248961895-403493d877b5?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 12,
    tmdb_id: 10402,
    slug: 'musica',
    name_es: 'Música',
    name_en: 'Music',
    description_es: 'Películas donde la música es la protagonista.',
    description_en: 'Movies where music takes center stage.',
    cover_image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200',
    status: 'published',
    sitemap_priority: 'medium'
  },
  {
    id: 13,
    tmdb_id: 9648,
    slug: 'misterio',
    name_es: 'Misterio',
    name_en: 'Mystery',
    description_es: 'Intrigas y enigmas que mantendrán tu mente activa hasta el final.',
    description_en: 'Intrigues and puzzles that will keep your mind active until the end.',
    cover_image_url: 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 14,
    tmdb_id: 10749,
    slug: 'romance',
    name_es: 'Romance',
    name_en: 'Romance',
    description_es: 'Historias de amor que conmueven el corazón.',
    description_en: 'Love stories that touch the heart.',
    cover_image_url: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 15,
    tmdb_id: 878,
    slug: 'ciencia-ficcion',
    name_es: 'Ciencia Ficción',
    name_en: 'Science Fiction',
    description_es: 'Futuros distópicos, viajes en el tiempo y tecnología avanzada.',
    description_en: 'Dystopian futures, time travel, and advanced technology.',
    cover_image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 16,
    tmdb_id: 10770,
    slug: 'tv-movie',
    name_es: 'Película de TV',
    name_en: 'TV Movie',
    description_es: 'Películas producidas para televisión.',
    description_en: 'Movies produced for television.',
    cover_image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200',
    status: 'published',
    sitemap_priority: 'low'
  },
  {
    id: 17,
    tmdb_id: 53,
    slug: 'thriller',
    name_es: 'Thriller',
    name_en: 'Thriller',
    description_es: 'Suspenso y tensión que te mantendrán al borde del asiento.',
    description_en: 'Suspense and tension that will keep you on the edge of your seat.',
    cover_image_url: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?w=1200',
    status: 'published',
    sitemap_priority: 'high'
  },
  {
    id: 18,
    tmdb_id: 10752,
    slug: 'guerra',
    name_es: 'Guerra',
    name_en: 'War',
    description_es: 'Historias de conflictos bélicos y el valor humano.',
    description_en: 'Stories of war conflicts and human valor.',
    cover_image_url: 'https://images.unsplash.com/photo-1580752300992-559f8e9cc97a?w=1200',
    status: 'published',
    sitemap_priority: 'medium'
  },
  {
    id: 19,
    tmdb_id: 37,
    slug: 'western',
    name_es: 'Western',
    name_en: 'Western',
    description_es: 'El viejo oeste con vaqueros, pistoleros y fronteras salvajes.',
    description_en: 'The old west with cowboys, gunslingers, and wild frontiers.',
    cover_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
    status: 'published',
    sitemap_priority: 'low'
  }
]
